# Generated by Django 5.2.8 on 2025-12-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='expected_output',
            field=models.TextField(default='', help_text='Ex: 15 (Must match exactly)'),
        ),
        migrations.AddField(
            model_name='question',
            name='input_data',
            field=models.TextField(blank=True, help_text='Ex: 5 10 (Optional)', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
