# Generated by Django 5.2.8 on 2025-12-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_question_expected_output_question_input_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Contest', max_length=100)),
                ('end_time', models.DateTimeField(help_text='Set the contest end time here')),
            ],
        ),
    ]
