# Generated by Django 5.2.8 on 2025-12-27 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contestsetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time_limit_minutes',
            field=models.IntegerField(default=10, help_text='Duration in minutes'),
        ),
        migrations.AlterField(
            model_name='contestsetting',
            name='end_time',
            field=models.DateTimeField(help_text='Global Contest End Time'),
        ),
        migrations.CreateModel(
            name='QuestionTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
